import Head from "next/head";
import { Sidebar } from "../components/Sidebar";
import { NoteSection } from "../components/NoteSection";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Maple Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" bg-slate-400 min-h-screen flex flex-col md:flex-row">
        <Sidebar />
        <NoteSection />
      </div>
    </div>
  );
}
