import Head from "next/head";
import { useAuth } from "../context/AuthContext";
export default function Home() {
  const { userToken } = useAuth();
  return (
    <div>
      <Head>
        <title>Maple Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <h1 className=" text-green-600 text-6xl">User Logged In</h1>
      </div>
      
    </div>
  );
}
