import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Maple Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className=" text-green-600">Hello</h1>
    </div>
  );
}
